version: "3"
services:
    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        environment:
            ENV_FILE_PATH: .docker.env

        entrypoint: "npm run start:dev"
        ports:
            - "3001:3001"
        volumes:
            - ./server:/usr/src/app
    client:
        build:
            context: ./client
            dockerfile: ./Dockerfile
        command: "npm run dev"
        ports:
            - "5173:5173"
        volumes:
            - ./client:/usr/src/app
    mongo:
        image: mongo
